version: '2'
services:

  ui:
    container_name: base-ui
    image: portainer/portainer:arm64
    restart: always
    environment:
      VIRTUAL_HOST: rpi.diehlabs.lan
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/data/config/portainer-arm64:/data
    expose:
      - 9000/tcp
    network_mode: bridge

  proxy:
    container_name: base-proxy
    image: armhfbuild/nginx
    environment:
      LETSENCRYPT_HOST: "home.diehlabs.tech,bi.diehlabs.tech"
      LETSENCRYPT_EMAIL: "cultclassik@gmail.com"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/config/proxy-arm/conf.d:/etc/nginx/conf.d
      - /mnt/data/config/proxy-arm/vhost.d:/etc/nginx/vhost.d
      - /mnt/data/config/proxy-arm/certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    network_mode: bridge

  dockergen:
    container_name: base-dockergen
    image: cultclassik/dockergen-armhf
    build: ./dockergen
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    entrypoint:
      - /usr/local/bin/docker-gen
      - -notify-sighup
      - base-proxy
      - -watch
      - -only-exposed
      - /etc/docker-gen/templates/nginx.tmpl
      - /etc/nginx/conf.d/default.conf
    depends_on:
      - proxy

  ssl:
    container_name: base-ssl
    image: cultclassik/letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: base-proxy
      NGINX_DOCKER_GEN_CONTAINER: base-dockergen
    volumes_from:
      - proxy
    volumes:
      - /mnt/data/config/proxy-arm/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    depends_on:
      - proxy
