version: '2'
services:
  # UI for Docker
  ui:
    container_name: base-ui
    image: hypriot/rpi-dockerui
    restart: always
    environment:
      VIRTUAL_HOST: rpi.diehlabs.lan
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    expose:
      - 9000/tcp
    network_mode: bridge

# need to add a file named [vhost fqdn name]_location with contents : proxy_set_header Connection $http_connection;
#  for docker ui to function correctly behind proxy

# docker run -d --expose=9000/tcp --name=docker-ui --restart=always -e VIRTUAL_HOST=rpi.diehlabs.lan -e VIRTUAL_PORT=9000 -v /etc/localtime:/etc/localtime:ro -v /var/run/docker.sock:/var/run/docker.sock:ro hypriot/rpi-dockerui
# docker run -d --expose=9000/tcp --name=docker-ui --restart=always -v /etc/localtime:/etc/localtime:ro -v /var/run/docker.sock:/var/run/docker.sock:ro hypriot/rpi-dockerui

  # nginx reverse proxy for access to container web uis
  # auto generates it's config with dockergen
  proxy:
    container_name: base-proxy
    image: braingamer/nginx-proxy-arm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /mnt/data/config/proxy-arm/vhost.d:/etc/nginx/vhost.d:ro
      - /mnt/data/config/proxy-arm/certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    network_mode: bridge

  ssl:
    container_name: base-ssl
    image: cultclassik/letsencrypt
    volumes_from:
      - proxy 
    volumes:
      - /mnt/data/config/proxy-arm/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
