version: '2'
services:
  # UI for Docker
  ui:
    container_name: base-ui
    image: portainer/portainer:arm64 
    restart: always
    environment:
      VIRTUAL_HOST: rpi.diehlabs.lan
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/data/config/portainer-arm64:/data
    expose:
      - 9000/tcp
    network_mode: bridge

  # nginx reverse proxy for access to container web uis
  # auto generates it's config with dockergen
  proxy:
    container_name: base-proxy
    image: braingamer/nginx-proxy-arm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /mnt/data/config/proxy-arm/vhost.d:/etc/nginx/vhost.d
      - /mnt/data/config/proxy-arm/certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    network_mode: bridge

  ssl:
    container_name: base-ssl
    image: cultclassik/letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: base-proxy 
    volumes_from:
      - proxy 
    volumes:
      - /mnt/data/config/proxy-arm/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    depends_on:
      - proxy
